-- Script Colocar Objeto 

local args = {
    [1] = game:GetService("Players").LocalPlayer.Toolbar.Spikes, -- Acesso
    [2] = Vector3.new(302.5, 38.79999923706055, 1822.5), -- Poss
    [3] = Vector3.new(0, 44.72301483154297, 0) -- Rotação
}

game:GetService("ReplicatedStorage").Network.Items.BuildItem:FireServer(unpack(args))

-- 

local args = {
    [1] = "resources",
    [2] = 3
}

game:GetService("ReplicatedStorage").Network.Items.CraftItem:FireServer(unpack(args))

-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "structures",
    [2] = 1
}

game:GetService("ReplicatedStorage").Network.Items.CraftItem:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "tools",
    [2] = 2
}

game:GetService("ReplicatedStorage").Network.Items.CraftItem:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "machines",
    [2] = 4
}

game:GetService("ReplicatedStorage").Network.Items.CraftItem:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Toolbar.Plastics,
    [2] = "Toolbar",
    [3] = 4
}

game:GetService("ReplicatedStorage").Network.Items.MoveItem:FireServer(unpack(args))

-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = -1.1
}

game:GetService("ReplicatedStorage").Network.Character.TakeStamina:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Inventory.Plastics,
    [2] = "Inventory",
    [3] = 10
}

game:GetService("ReplicatedStorage").Network.Items.MoveItem:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = 2
}

game:GetService("ReplicatedStorage").Network.Items.EquipItem:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Toolbar:FindFirstChild("Wooden Wall"),
    [2] = Vector3.new(462, 36.70000076293945, 1531.5),
    [3] = Vector3.new(0, 153.9981231689453, 0)
}

game:GetService("ReplicatedStorage").Network.Items.BuildItem:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = workspace.Built:FindFirstChild("Big Furnace"),
    [2] = "MoveItem",
    [3] = workspace.Built:FindFirstChild("Big Furnace").Raw:FindFirstChild("Iron Ore"),
    [4] = "Raw",
    [5] = 5
}

game:GetService("ReplicatedStorage").Network.Items.ItemAction:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

function getNil(name,class) for _,v in pairs(getnilinstances())do if v.ClassName==class and v.Name==name then return v;end end end

local args = {
    [1] = getNil("Basic Turret", "Folder"),
    [2] = Vector3.new(446, 48.900001525878906, 1515),
    [3] = Vector3.new(0, -37.43256378173828, 180)
}

game:GetService("ReplicatedStorage").Network.Items.BuildItem:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = workspace.Spawned.RareLoot,
    [2] = workspace.Spawned.RareLoot.Inventory
}

game:GetService("ReplicatedStorage").Network.Items.TakeAll:FireServer(unpack(args))

-- Script generated by SimpleSpy - credits to exx#9394

function getNil(name,class) for _,v in pairs(getnilinstances())do if v.ClassName==class and v.Name==name then return v;end end end

local args = {
    [1] = getNil("Scrap", "Folder")
}

game:GetService("ReplicatedStorage").Network.Items.DropItem:FireServer(unpack(args))
