-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "click",
    [2] = workspace.Spawned.CopperOre,
    [3] = false
}

game:GetService("ReplicatedStorage").Network.Items.ToolAction:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "click",
    [2] = {
        [1] = Vector3.new(1384.13037109375, 15.537001609802246, 1193.270263671875),
        [2] = Vector3.new(1542.1734619140625, 30.573013305664062, 1140.277099609375),
        [3] = workspace.Spawned.Tree1.TreeTrunk,
        [4] = 300,
        [5] = {
            ["magAmmo"] = 15,
            ["recoilSpeed"] = 0.5,
            ["magazine"] = game:GetService("ReplicatedStorage").Bullets.Glock17.Magazine,
            ["playerDamage"] = 7,
            ["reloadTime"] = 3,
            ["bullet"] = game:GetService("ReplicatedStorage").Bullets.Glock17.ShootBullet,
            ["recoilIntensity"] = 1,
            ["bulletSpeed"] = 300,
            ["buildableDamage"] = 5,
            ["dropBullet"] = game:GetService("ReplicatedStorage").Bullets.Glock17.DropBullet,
            ["deflection"] = 2,
            ["damage"] = 120
        },
        [6] = 120
    }
}

game:GetService("ReplicatedStorage").Network.Items.ToolAction:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "click",
    [2] = workspace.Spawned.IronOre,
    [3] = false
}

game:GetService("ReplicatedStorage").Network.Items.ToolAction:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "defense",
    [2] = 3
}

game:GetService("ReplicatedStorage").Network.Items.CraftItem:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "defense",
    [2] = 4
}

game:GetService("ReplicatedStorage").Network.Items.CraftItem:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = 2
}

game:GetService("ReplicatedStorage").Network.Items.EquipItem:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "click",
    [2] = workspace.Spawned.Palm1,
    [3] = false
}

game:GetService("ReplicatedStorage").Network.Items.ToolAction:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "click",
    [2] = workspace.Spawned.Tree1,
    [3] = false
}

game:GetService("ReplicatedStorage").Network.Items.ToolAction:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Toolbar.Spikes,
    [2] = Vector3.new(302.5, 38.79999923706055, 1822.5),
    [3] = Vector3.new(0, 44.72301483154297, 0)
}

game:GetService("ReplicatedStorage").Network.Items.BuildItem:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "defense",
    [2] = 1
}





-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "click",
    [2] = workspace.Enemies:FindFirstChild("Mutant Zombie")
}

game:GetService("ReplicatedStorage").Network.Items.ToolAction:FireServer(unpack(args))

















game:GetService("ReplicatedStorage").Network.Items.CraftItem:FireServer(unpack(args))
